project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "NHANES Weight History"
  author:
    - Yunqing Qiu (yq2374)
    - Xinyi Chen (xc2719)
  repo-url: https://github.com/YunjiQ/NHANESweight
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


