# Introduction

How do you consider your weight? Have you ever tried to lose weight in the past few years? It is interesting to observe that weight loss has become a prevalent concern in the lives of many adults. More and more people started to lose weight and focus on achieving a balanced and fit body, which prompted a growing interest in scientific and efficient methods to achieve this goal.

The National Health and Nutrition Examination Survey (NHANES) is a program conducted by the National Center for Health Statistics (NCHS), which is part of the Centers for Disease Control and Prevention (CDC) in the United States. Under the guidance of the CDC, NHANES empowers researchers, policymakers, and healthcare professionals with the tools to understand health trends, identify emerging issues, and tailor interventions to the specific needs of diverse populations.

Recognizing the significance of this health endeavor, the NHANES conducted a survey on the weight history on a two-year cycle basis to keep the information updated. The survey targeted thousands of participants aged 16 years and older, encompassing individuals with diverse habits and racial backgrounds. The primary objective of this survey is to investigate the dynamics of weight loss during the past 12 months and explore the methods that are endeavored by its participants to lose or maintain their weight.

With the survey data from NHANES, we can gain some insights from exploring this large sample. In this project, we will be practically interested in exploring the effective impact factors of weight loss, answering questions like how psychological intent promotes the performance of weight loss, whether a strict diet helps lose weight, and what kind of dietary habit would benefit weight loss. We will focus on the questionnaire data, which indicates the self-reported weight changes and some related factors. We will conduct data pre-processing, trend analysis, correlation study, and statistic tests. According to the research on the data set, we will be able to conclude the most obvious and possible method or combination of methods for controlling the weights.
